default_install_hook_types: [pre-commit, pre-push]
minimum_pre_commit_version: 2.18.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-added-large-files
      args:  ['--maxkb=1024']
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2
    hooks:
      - id: ruff
        alias: fix-imports
        name: ruff-fix-imports
        args: [ --select, I, --fix, --show-fixes]
      - id: ruff
        alias: lint-code
        name: ruff-lint-code
        args: [--show-fixes]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
    - id: poetry-check
