site_name: Custom Notes
site_url: https://ronakr14.github.io/Custom-Notes/
theme:
  name: material

  language: en

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: black
      accent: white
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode    
      primary: black
      accent: white
    
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

nav:
  - Home: index.md
  - Tutorials:
    - Tutorials Home Page: tutorials/index.md
    - Application Programming Interface: tutorials/application_programming_interface/index.md
    - Artificial Intelligence: tutorials/artificial_intelligence/index.md
    - Blockchain: tutorials/blockchain/index.md
    - Cloud Ecosystems: tutorials/cloud_ecosystems/index.md
    - Data Architecture: tutorials/data_architecture/index.md
    - Data Engineering: tutorials/data_engineering/index.md
    - DevOps & GitOps: tutorials/devops_gitops/index.md
    - Ethical Hacking: tutorials/ethical_hacking/index.md
    - Languages: tutorials/languages/index.md
    - Operating Systems: tutorials/operating_systems/index.md
    - Quantum Computing: tutorials/quantum_computing/index.md
    - Version Control Systems: tutorials/version_control_systems/index.md
  - Custom Libraries: custom_libraries/index.md
  - Code Snippets: code_snippets/index.md
  - Portfolio: https://ronakr14.github.io
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ronakr14
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ronak-rathore05/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/rastar14
    - icon: fontawesome/brands/python
      link: https://pypi.org/user/RonakR/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/rastar14/

copyright: |
  &copy; 2024=5 <a href="https://github.com/ronakr14"  target="_blank" rel="noopener">Ronak Rathore</a>