site_name: Collectives
theme:
  name: material
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: white
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: white
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

plugins:
  - mkdocstrings
  - search

nav:
  - Artificial Intelligence: artificial_intelligence/index.md
  - Languages: languages/index.md
  - Database and Data Warehouse: database_datawarehouse/index.md
  - Container: https://ronakr14.github.io/Containers/
  - Version Control Systems: https://ronakr14.github.io/Version-Control-Systems/
  - Projects: projects/index.md
  - API: api/index.md
  - Operating Systems: https://ronakr14.github.io/Operating-Systems/
  - Cloud Technologies: https://ronakr14.github.io/Cloud-Technologies/
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ronakr14

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


copyright: |
  &copy; 2024 <a href="https://github.com/ronakr14"  target="_blank" rel="noopener">Ronak Rathore</a>